Iter14
e-pas/yandex-praktikum-shortener pull request #12
Opened 2023-04-30 08:30 UTC by e-pas

2023-05-03 23:00 UTC, tmvrus requested changes

2023-05-03 23:00 UTC, tmvrus commented on internal/app/service/service.go
> +	errs := proc.ProceedWith(shortURLs)
какой вы этом смысл?

2023-05-03 23:00 UTC, tmvrus commented on internal/app/service/service.go
> +func (s *Service) DeleteURLs(ctx context.Context, shorts []string) error {
этот вызов синхронный, по условию инкремента удаление должно осуществляться независимо от обработки входящего запроса

2023-05-04 05:06 UTC, e-pas commented on internal/app/service/service.go
> +	errs := proc.ProceedWith(shortURLs)
Ведь в многопоточном режиме можно не только помечать на удаление какие-то данные, но можно и сделать какую-то более сложную функцию (например проверить живы ли исходные url и т.п.). Для этого достаточно передать в NewProcessor другую callback функцию вместо markDeleted. Для того, чтобы была какая-то обратная связь собираю ошибки, возвращенные callback функцией, чтобы их можно было как-то обработать в дальнейшем.

2023-05-04 05:35 UTC, e-pas commented on internal/app/service/service.go
> +func (s *Service) DeleteURLs(ctx context.Context, shorts []string) error {
Вся паралельная работа со структурой хранения URL, вынесена в отдельный файл (fanout.go). Но задача по удалению url примитивная и выполняется очень быстро. Поэтому, вызов паралельной обработки я сделал синхронный, чтобы можно было обработать и вернуть ошибки в ответ на запрос.
Для ассинхронного вызова, достаточно вызвать NewProcessor/ProceedWith в горутине. Тогда, правда, уходит дальнейшая работа по обработке результатов/ошибок выполнения.
Замечание учел, вызов функций поправил.

2023-05-06 17:08 UTC, tmvrus approved these changes

2023-05-07 07:49 UTC, merged